### PR TITLE
fixed: apply roomscale movement scaling before world rotation

### PR DESCRIPTION
**Pull request by jpfx1342**
Fixes issue #257

### CODE REVIEW

**Comment by jrbudda** [comment]
I added your changes manually. Please don't be offended I'm closing your pull request. (the 'patch' system this thing uses for github is horrendous for collaboration). I appreciate you tracking down this bug. You'll get a shout out in the patch notes.

**Comment by jpfx1342** [comment]
It's alright. I tried to make sure my diff was as clean as possible, but I understand if you're having trouble.

**Comment by jrbudda** [comment]
It would likely be fine, especially on that file, which isn't actually patched. Just standard operating procedure now after some ugly collision incidents when we were first starting out.

**Comment by Techjar** [comment]
Yeah, this repository is essentially a diff within a diff (Git itself being the latter), and that does nasty things when merging commits.

**Pull request closed without merging**
