### PR TITLE
Fixes for Linux

### PR DESCRIPTION
**Pull request by valentindavid**
Here are the two fixes to run on Linux. The stencil test might be only NVidia related. The other is fixing alignment for the data structures for OpenVR. There might be better solution to fix generated code. But at least it gives an idea.

### CODE REVIEW

**Comment by Techjar** [comment]
We don't accept PRs here because it causes a mess, but I'll merge these changes in manually and test (to be sure nothing breaks on windows).

**Comment by Techjar** [comment]
The problem with your AlignedStructure change is most of the jopenvr code is generated by jnaerator, so changing it manually makes it harder for us to update it. Can you find an alternative way of doing it that doesn't require changing every file?

It also appears to be OS-specific based on openvr.h, so it probably break on windows in its current state.

**Comment by Techjar** [comment]
I think this may actually be a bug in the JNA library.

**Comment by Techjar** [comment]
The JNA library should be handling the alignment internally, I looked over the code. Not really sure what's going on there, but this is not a fix I'm happy with since it's basically a hack.

**Comment by Techjar** [comment]
Perhaps there is actually a bug in the JNA library. Can you open up an issue on that repo, and provide more details about this alignment issue? You seem to understand more about than I do, and I'd like to actually fix this in the library rather than working around it in our code. https://github.com/java-native-access/jna

**Comment by valentindavid** [comment]
Unfortunately there is no bug in JNA. Openvr uses #pragma pack(4). This is not standard. JNA should not handle that by default. It should be the responsability of the binding the specify exotic alignment.

**Comment by Techjar** [comment]
Ah, I misunderstood. Well that's a pain in the ass.

**Comment by valentindavid** [comment]
We could try to fix JNAerator to handle #pragma pack. But the cost of fixing it seems to me too big compared to how specific and unusual openvr is.

**Comment by valentindavid** [comment]
I was also really pissed when I saw the #pragma pack.

**Comment by Techjar** [comment]
JNAerator kind of sucks honestly, but it's all we've got. It doesn't even handle const correctly, just throws them out. So all the const values need to be manually copied over.

**Comment by Techjar** [comment]
Can you generate a patch file for commit `b76ae8a`? It will make it much easier for me to apply.

**Comment by Techjar** [comment]
Did it myself, it's merged now. @jrbudda can push the code to this repo later (we work on a private repo with full minecraft source because patch files cause conniptions).

**Comment by jrbudda** [comment]
I don't think the PR would have hurt anything changing one line in the entityrenderer patch :P. I'll push this in a second.

**Comment by Techjar** [comment]
That's not the problem. The problem is running applychanges with desynced repos, causes you to lose changes. It's just best to avoid doing that.

**Comment by jrbudda** [comment]
heres a test build for 1.11.2
[vivecraft-1.11.2-jrbudda-8r1-installer.jar.zip](https://github.com/jrbudda/minecrift/files/856815/vivecraft-1.11.2-jrbudda-8r1-installer.jar.zip)

**Comment by valentindavid** [comment]
Great. I will give it a try this evening.

**Pull request closed without merging**
