### PR TITLE
SteamVR keyboard now opens automatically in sign and book UIs

### PR DESCRIPTION
**Pull request by Techjar**
Yeah this was super simple to add. I checked GuiEditSign for any Forge stuff and, as suspected, it's totally untouched. This fixes issue #57

### CODE REVIEW

**Comment by Techjar** [comment]
Actually, hold up before you merge this. I'm going to add it for books as well.

**Comment by jrbudda** [comment]
I take it guieditsign has no forge hooks. Is the books the same?

**Comment by jrbudda** [comment]
jinx

**Comment by Techjar** [comment]
Yeah neither of them have any Forge hooks. Slight issue though, the keyboard opens in front of half the book UI. Any way to give the book UI an offset when it opens, like the chat does?

**Comment by jrbudda** [comment]
Yes in MCOpenVR around line 1577 is where I'm already doing the same sorta thing for the chat window. I really should be moving the 'keyboard' around but that's a whole nother OpenVR call and coordinate translation step.

**Comment by Techjar** [comment]
Okay, there, now it's ready to be merged. I put the offset stuff in and played with the values a bit until it looked good.

**Pull request merged**
